### ISSUE TITLE
cloud-init/fabric MUST create symlinks to some kernel files (details within)

### ISSUE THREAD

**Issue by InBrewJ** [LUSHDigital/lrpi_base#5]

**Comment by InBrewJ** [comment]
In /opt/vc/lib of Hypriot v1.9.0:
sudo ln -s libbrcmEGL.so libEGL.so
sudo ln -s libbrcmGLESv2.so libGLESv2.so
sudo ln -s libbrcmOpenVG.so libOpenVG.so
sudo ln -s libbrcmWFC.so libWFC.so

**Comment by InBrewJ** [comment]
Actually an issue for lrpi_bootstrap/fabfile.py

Add in another function and add it to prepare_card_2()

Also try and eliminate sudo("sudo .....") - there should only be one sudo!

**Comment by pisuke** [comment]
No longer using cloud-init.
